### ISSUE TITLE
brew install hangs on make install

### ISSUE THREAD

**Issue by ghost** [codeclimate/homebrew-formulae#26] opened 2016-07-21 02:23 UTC
Trying to `brew install codeclimate` hangs at the `make install` step. No further output is displayed. Build does not complete.

```
brew install codeclimate
==> Installing codeclimate from codeclimate/formulae
==> Downloading https://github.com/codeclimate/codeclimate/archive/v0.35.1.tar.gz
Already downloaded: /Users/bm5k/Library/Caches/Homebrew/codeclimate-0.35.1.tar.gz
==> make install
```

I let it sit like this for about an hour. No change. Also verified there was no network activity & no CPU load.

**Comment by wfleming** [comment] 2016-07-21 02:53
Hi @BM5k,

Sorry for the trouble here. You may be hitting something similar to #21: hangs like this on OS X are often because `docker-machine` VMs have an odd habit of losing some network connectivity. The first thing I would suggest trying is restarting the VM your docker server is running on. E.g. if you're using docker-machine, run the `docker-machine restart` command. Please try that, and if that doesn't make a difference let me know.

**Comment by ghost** [comment] 2016-07-21 03:11
I'm using the docker for mac beta; I've restarted both docker & my mac with the same results.

**Comment by wfleming** [comment] 2016-07-21 14:37
Ok, sorry that didn't help. I think the next step should be to run the commands directly to see what's hanging.

You can open up the tarzip that got downloaded to `/Users/bm5k/Library/Caches/Homebrew/codeclimate-0.35.1.tar.gz`, cd into the directory, and run `make install` directly and see if that also hangs without output.

If that does hang without output, it'd be good to then run `bin/check` from that directory and see if that hangs.

While discussing this in the office we noticed that part of that `make install` rule is to pull all of the individual analysis engines we support. That step can take quite a long time, because we have so many engines. The decision to install them all at install time was made when we had far fewer of them, but it's doesn't seem appropriate to keep doing that. Your issue may turn out to be that that step can take a very long time, and that the Homebrew formulae doesn't indicate any progress while doing that. We're looking into changing this behavior, regardless. The debugging steps I suggested above will help us better understand if this is what's going on or if there's a hang talking to the docker server or something similar. Thanks for your patience here.

**Comment by ghost** [comment] 2016-07-21 17:36
In case it helps, I was able to get everything working without homebrew by running

```
docker pull codeclimate/codeclimate

docker run \                                                                                                                                                 2.3.1
  --interactive --tty --rm \          
  --env CODE_PATH="$PWD" \
  --volume "$PWD":/code \
  --volume /var/run/docker.sock:/var/run/docker.sock \
  --volume /tmp/cc:/tmp/cc \
  codeclimate/codeclimate
```

manually.

I will try running the `make install` manually as you suggested.

**Comment by ghost** [comment] 2016-07-21 18:42
OK, I tried running `make install` manually. The first time, I received a network error:

```
$ make install
bin/check
docker pull codeclimate/codeclimate:latest
Pulling repository docker.io/codeclimate/codeclimate
Network timed out while trying to connect to https://index.docker.io/v1/repositories/codeclimate/codeclimate/images. You may want to check your internet connection or if you are behind a proxy.
make: *** [install] Error 1
```

I then tried running `docker pull` manually & it worked

```
$ docker pull codeclimate/codeclimate:latest
latest: Pulling from codeclimate/codeclimate

Digest: sha256:e3bafd05b5dacf633961b03cb60a508f3531e06394e74a0d5306cfd9002fe4ab
Status: Image is up to date for codeclimate/codeclimate:latest
```

After that, `make install` seemed to work also:

```
$ make install
bin/check
docker pull codeclimate/codeclimate:latest
latest: Pulling from codeclimate/codeclimate

Digest: sha256:e3bafd05b5dacf633961b03cb60a508f3531e06394e74a0d5306cfd9002fe4ab
Status: Image is up to date for codeclimate/codeclimate:latest
Using default tag: latest
latest: Pulling from codeclimate/codeclimate-duplication

Digest: sha256:b63a71a598635fe828810241f7da9de4a7a16e5354f101f93ee8d7fd8fea9e6b
Status: Image is up to date for codeclimate/codeclimate-duplication:latest
Using default tag: latest
latest: Pulling from codeclimate/codeclimate-rubocop

Digest: sha256:a813cedaf53cb975b33be0b1fd2e6877bbb901731df55046a0ee7fbe941c8cb8
Status: Image is up to date for codeclimate/codeclimate-rubocop:latest
Using default tag: latest
latest: Pulling from codeclimate/codeclimate-bundler-audit

Digest: sha256:a014f2e8bae3afed42a20408d8e26faf868d4e64973ffe3662c0eb983648a735
Status: Image is up to date for codeclimate/codeclimate-bundler-audit:latest
Using default tag: latest
latest: Pulling from codeclimate/codeclimate-fixme

Digest: sha256:7a97f603f9ae200dc3604fe5531a11c33d3d5220fae03fb2ca79f532cc497aed
Status: Image is up to date for codeclimate/codeclimate-fixme:latest
Using default tag: latest
latest: Pulling from codeclimate/codeclimate-eslint

ac6ed54e68ca: Already exists 
a3ed95caeb02: Already exists 
df15d95af5ae: Already exists 
b05f1974d12f: Already exists 
5175576fe1b6: Already exists 
7402e3b8323e: Already exists 
1dd3085a4eff: Already exists 
086859be8bf2: Already exists 
f14d6b23989c: Already exists 
Digest: sha256:6a5ade4996ef4925e088d7606fa26693c4762220a3105f06731a0e901d180c2a
Status: Image is up to date for codeclimate/codeclimate-eslint:latest
Using default tag: latest
latest: Pulling from codeclimate/codeclimate-coffeelint

f5f17db9ef7c: Already exists 
b323df73e6c4: Already exists 
0fabb5fa5487: Already exists 
a3ed95caeb02: Already exists 
4e8ba7818f0c: Already exists 
3bb674e7e848: Already exists 
2b8f4309b6cc: Already exists 
d6f0df8ebf86: Already exists 
b01f44a12f3a: Already exists 
Digest: sha256:86e6f95bbe1edb52de750451cb28468731d1e4e7a1d04b28fe0398cf05f731e1
Status: Image is up to date for codeclimate/codeclimate-coffeelint:latest
Using default tag: latest
latest: Pulling from codeclimate/codeclimate-brakeman
d4bce7fd68df: Already exists 
a3ed95caeb02: Already exists 
dbb45873279c: Already exists 
379e35c55d3e: Already exists 
90b2691effa3: Already exists 
9ed71a5ff767: Already exists 
0fbabb9e7371: Already exists 
2d69e2094dd3: Already exists 
9c359a171804: Already exists 
0323f9955725: Already exists 
b916acd0b6c9: Already exists 
bbc23070f496: Already exists 
Digest: sha256:b49e57beff88a6f6440c291d2a5dfc8df9526fae12a197290cd9c99f18a0571e
Status: Image is up to date for codeclimate/codeclimate-brakeman:latest
Using default tag: latest
latest: Pulling from codeclimate/codeclimate-csslint
f5f17db9ef7c: Already exists 
b323df73e6c4: Already exists 
0fabb5fa5487: Already exists 
a3ed95caeb02: Already exists 
693a92aaa79b: Already exists 
322179af2b37: Already exists 
9069d6d7c2ca: Already exists 
09a098087abc: Already exists 
27a053897118: Already exists 
7ff24fb4519f: Already exists 
Digest: sha256:df5d764b5088dd2cae34df9a0cc73e99678fb83f90779ddcdb17affbd5ccda15
Status: Image is up to date for codeclimate/codeclimate-csslint:latest
mkdir -p /usr/local/bin
install -m 0755 codeclimate-wrapper /usr/local/bin/codeclimate
```

**Comment by dblandin** [comment] 2016-10-03 16:10
Going to go ahead and close this issue as it seems like it was caused by either network issues or some oddness using Docker for Mac Beta. Let us know if that's not the case!

**Closed as completed by dblandin** 2016-10-03 16:10 UTC
